services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\Payment\OGone:
        arguments:
            $options: []
            $formFactory: '@form.factory'
        tags:
            - { name: pimcore_ecommerce.payment.provider, key: 'ogone' }

    Pimcore\Bundle\EcommerceFrameworkBundle\OGone\Installer:
        public: true
